# Generated by Django 5.2.8 on 2025-11-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Дата и время синхронизации",
                    ),
                ),
                (
                    "added_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество добавленных"
                    ),
                ),
                (
                    "updated_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество обновленных"
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат синхронизации",
                "verbose_name_plural": "Результаты синхронизации",
                "ordering": ["-executed_at"],
            },
        ),
    ]
