# Generated by Django 5.2.8 on 2025-11-14 04:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "external_id",
                    models.UUIDField(
                        db_index=True, unique=True, verbose_name="ID в провайдере"
                    ),
                ),
            ],
            options={
                "verbose_name": "Площадка",
                "verbose_name_plural": "Площадки",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(
                        db_index=True, unique=True, verbose_name="ID в провайдере"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "event_date",
                    models.DateTimeField(db_index=True, verbose_name="Дата проведения"),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        db_index=True, verbose_name="Дата изменения у провайдера"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Открыто"), ("closed", "Закрыто")],
                        default="open",
                        max_length=6,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="events.venue",
                        verbose_name="Площадка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
                "ordering": ["-event_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=128, verbose_name="Имя регистрирующегося"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Электронная почта"),
                ),
                (
                    "confirmation_code",
                    models.CharField(max_length=12, verbose_name="Код подтверждения"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Время отправки подтверждающего кода",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                        verbose_name="Событие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Регистрация",
                "verbose_name_plural": "Регистрации",
                "indexes": [
                    models.Index(
                        fields=["event", "email"], name="events_even_event_i_8859f3_idx"
                    )
                ],
                "unique_together": {("event", "email")},
            },
        ),
    ]
