# Generated by Django 5.2.8 on 2025-11-17 16:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Outbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Топик"
                    ),
                ),
                ("payload", models.JSONField(verbose_name="Тело сообщения (payload)")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает отправки"),
                            ("processing", "В обработке"),
                            ("sent", "Отправлено"),
                            ("failed", "Ошибка"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="Статус доставки",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество попыток"
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True, default="", verbose_name="Последняя ошибка"
                    ),
                ),
            ],
            options={
                "verbose_name": "Outbox сообщение",
                "verbose_name_plural": "Outbox сообщения",
            },
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
